### ISSUE TITLE
kmerid error message

### ISSUE THREAD

**Issue by yingeddi2008** [phe-bioinformatics/kmerid#3]
Hi,

After knowing I should use more than 1 genome as the reference set, I successfully format three different species of Haemophilus and use pair-end reads as the query in the kmerid.py. But I have the following error message.

```
$ python /N/u/dongq/Carbonate/tools/kmerid/kmerid.py -f NZ_PNGS01000001.pe.sim.fastq.gz --config=/N/u/dongq/Carbonate/tools/kmerid/config/config.cnf
Traceback (most recent call last):
  File "/N/u/dongq/Carbonate/tools/kmerid/kmerid.py", line 209, in <module>
    main()
  File "/N/u/dongq/Carbonate/tools/kmerid/kmerid.py", line 62, in main
    checkMixing(aResults, fTmpFile, oConf)
  File "/N/u/dongq/Carbonate/tools/kmerid/kmerid.py", line 158, in checkMixing
    aTopHit = aRes[0]
IndexError: list index out of range
```
Could you please check what I did wrong?

my config file is the following:

```
[group_folders]
haemophilus_parainfluenzae = /N/dc2/scratch/dongq/IUMP/kmerid/ref/Haemophilus_parainfluenzae
haemophilus_influenzae = /N/dc2/scratch/dongq/IUMP/kmerid/ref/Haemophilus_influenzae
haemophilus_quentini = /N/dc2/scratch/dongq/IUMP/kmerid/ref/Haemophilus_quentini

[matrices]
haemophilus_parainfluenzae = config/haemophilus_parainfluenzae_simmat.tsv
haemophilus_influenzae = config/haemophilus_influenzae_simmat.tsv
haemophilus_quentini = config/haemophilus_quentini_simmat.tsv

[haemophilus_parainfluenzae_centroids]
1 = NZ_JVSB01000008.1
2 = NZ_LZMY01000001.1
3 = NZ_JVYT01000008.1

[haemophilus_parainfluenzae_refset]
1 = NZ_JWCE01000012.1
2 = NC_015964.1
3 = NZ_AFQS01000019.1
4 = NZ_JVPX01000001.1
5 = NZ_JVFE01000020.1
6 = NZ_JVSB01000008.1
7 = NZ_JVRH01000005.1
8 = NZ_JUTJ01000001.1
9 = NZ_AJTC01000001.1
10 = NZ_LZMY01000001.1
11 = NZ_JVSU01000011.1
12 = NZ_MPJK01000001.1
13 = NZ_JUOR01000001.1
14 = NZ_MAQD01000001.1
15 = NZ_LFXN01000001.1
16 = NZ_GL872339.1
17 = NZ_JVHG01000005.1
18 = NZ_JVSL01000004.1
19 = NZ_LZMW01000001.1
20 = NZ_PNGS01000001.1
21 = NZ_AJMW01000001.1
22 = NZ_JVYT01000008.1
23 = NZ_LZMX01000001.1
24 = NZ_MPJJ01000001.1

[haemophilus_influenzae_centroids]
1 = NC_014920.1
2 = NZ_CP020006.1
3 = NC_022356.1

[haemophilus_influenzae_refset]
1 = NZ_CP009610.1
2 = NC_014920.1
3 = NZ_CP008740.1
4 = NZ_CP020008.1
5 = NZ_CP020411.2
6 = NZ_CP017811.1
7 = NZ_LN831035.1
8 = NZ_ACSL01000041.1
9 = NC_017451.1
10 = NZ_CP020013.1
11 = NZ_CP020014.1
12 = NC_016809.1
13 = NZ_CP007470.1
14 = NZ_CP020012.1
15 = NC_007146.2
16 = NZ_CP007805.1
17 = NC_000907.1
18 = NZ_CP020006.1
19 = NZ_CP007472.1
20 = NC_022356.1
21 = NZ_CP020010.1
22 = NZ_CP007471.1
23 = NZ_CP020009.1
24 = NZ_CP020011.1
25 = NC_017452.1
26 = NZ_CP020007.1
27 = NC_014922.1

[haemophilus_quentini_centroids]
1 = NZ_MDJB01000001.1

[haemophilus_quentini_refset]
1 = NZ_MDJB01000001.1
2 = NZ_MCII02000001.1
3 = NZ_MDJC01000001.1
```

Thanks,

Eddi

**Comment by ulfschaefer** [comment]
This happens when the kmer similarity comparison does not give any results. The aRes list appears to be empty.

Can you check that your group folders contain all files required. You should have one file ending in "_kmers.txt" for every file mentioned in your config.cnf. E.g. "NZ_GL872339.1_kmers.txt". These files should be quiet large, maybe about 20MB for H. influenzae.

If they are absent or empty, it might be because your reference genomes don't have the correct ending. I believe they must end in "fa", "fna", "fas", or "fasta" (optionally plus ".gz"). So it must be NZ_GL872339.1.fasta for example. 

If you rename your references and delete all _kmers.txt files and all _simmat.tsv files and your config file and setup your references again, it should work.

Sorry if this wasn't clear from the readme.

**Comment by yingeddi2008** [comment]
Hi,

Yes, I do have the fasta files and the *_kmer.txt as listed below:

$ ls -hl */*

-rw-r--r-- 1 dongq faculty 1.8M Aug 15 16:19
Haemophilus_influenzae/NC_000907.1.fna

-rw-r--r-- 1 dongq faculty  20M Aug 15 16:40
Haemophilus_influenzae/NC_000907.1_kmers.txt

-rw-r--r-- 1 dongq faculty 1.9M Aug 15 16:19
Haemophilus_influenzae/NC_007146.2.fna

-rw-r--r-- 1 dongq faculty  21M Aug 15 16:40
Haemophilus_influenzae/NC_007146.2_kmers.txt

-rw-r--r-- 1 dongq faculty 2.0M Aug 15 16:19
Haemophilus_influenzae/NC_014920.1.fna

-rw-r--r-- 1 dongq faculty  22M Aug 15 16:39
Haemophilus_influenzae/NC_014920.1_kmers.txt

-rw-r--r-- 1 dongq faculty 2.0M Aug 15 13:10
Haemophilus_influenzae/NC_014922.1.fasta

-rw-r--r-- 1 dongq faculty  22M Aug 15 16:41
Haemophilus_influenzae/NC_014922.1_kmers.txt

-rw-r--r-- 1 dongq faculty 2.0M Aug 15 16:19
Haemophilus_influenzae/NC_016809.1.fna

-rw-r--r-- 1 dongq faculty  22M Aug 15 16:40
Haemophilus_influenzae/NC_016809.1_kmers.txt

-rw-r--r-- 1 dongq faculty 1.9M Aug 15 16:19
Haemophilus_influenzae/NC_017451.1.fna

-rw-r--r-- 1 dongq faculty  21M Aug 15 16:39
Haemophilus_influenzae/NC_017451.1_kmers.txt

-rw-r--r-- 1 dongq faculty 1.8M Aug 15 16:19
Haemophilus_influenzae/NC_017452.1.fna

-rw-r--r-- 1 dongq faculty  20M Aug 15 16:41
Haemophilus_influenzae/NC_017452.1_kmers.txt

-rw-r--r-- 1 dongq faculty 1.8M Aug 15 16:19
Haemophilus_influenzae/NC_022356.1.fna

-rw-r--r-- 1 dongq faculty  20M Aug 15 16:40
Haemophilus_influenzae/NC_022356.1_kmers.txt

-rw-r--r-- 1 dongq faculty 1.9M Aug 15 16:19
Haemophilus_influenzae/NZ_ACSL01000041.1.fna

-rw-r--r-- 1 dongq faculty  21M Aug 15 16:39
Haemophilus_influenzae/NZ_ACSL01000041.1_kmers.txt

-rw-r--r-- 1 dongq faculty 1.8M Aug 15 16:19
Haemophilus_influenzae/NZ_CP007470.1.fna

-rw-r--r-- 1 dongq faculty  20M Aug 15 16:40
Haemophilus_influenzae/NZ_CP007470.1_kmers.txt

-rw-r--r-- 1 dongq faculty 1.8M Aug 15 16:19
Haemophilus_influenzae/NZ_CP007471.1.fna

-rw-r--r-- 1 dongq faculty  20M Aug 15 16:40
Haemophilus_influenzae/NZ_CP007471.1_kmers.txt

-rw-r--r-- 1 dongq faculty 1.9M Aug 15 16:19
Haemophilus_influenzae/NZ_CP007472.1.fna

-rw-r--r-- 1 dongq faculty  21M Aug 15 16:40
Haemophilus_influenzae/NZ_CP007472.1_kmers.txt

-rw-r--r-- 1 dongq faculty 1.8M Aug 15 16:19
Haemophilus_influenzae/NZ_CP007805.1.fna

I believed that I followed the readme file religiously. What other files I
can give you to provide the same error message? I can zip up all my
reference and input reads and share a link to you for you to run. Is that
OK?

Thanks,

Eddi
